# vim: nospell
#
language: minimal
dist: trusty
sudo: required

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - .stack-work/install

before_cache:
  - rm -rf $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

    packages: &apt_packages
      - g++-4.8
      - libgmp-dev
      - happy-1.19.5
      - alex-3.1.7
      - libblas-dev
      - liblapack-dev

matrix:
  include:
    - env: GHC=7.10.3 CABAL=1.22 LLVM=4.0.0 CUDA=8.0.61-1
      compiler: "GHC 7.10"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-1.22
            - llvm-4.0-dev

    - env: GHC=8.0.2 CABAL=1.24 LLVM=4.0.0 CUDA=8.0.61-1
      compiler: "GHC 8.0"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-1.24
            - llvm-4.0-dev

    - env: GHC=8.2.2 CABAL=2.0 LLVM=5.0.0 CUDA=8.0.61-1
      compiler: "GHC 8.2"
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - cabal-install-2.0
            - llvm-5.0-dev

    # - env: GHC=head CABAL=head LLVM=3.9.1
    #   compiler: "GHC HEAD"
    #   addons: { apt: { sources: [ hvr-ghc, ubuntu-toolchain-r-test ], packages: [ nvidia-cuda-toolkit, g++-4.8, ghc-head, cabal-install-head, happy-1.19.5, alex-3.1.7 ] }}

  # allow_failures:
  #   - env: GHC=head CABAL=head LLVM=3.9.1

  fast_finish: true

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$HOME/.cabal/bin:$PATH
  # - |
  #     case ${GHC} in
  #       7.8.*) export UPGRADE_CABAL=1 ;;
  #     esac
  # - |
  #     case ${LLVM} in
  #       3.5.*) source .travis/install-llvm-trusty.sh ;;
  #     esac
  - source .travis/install-cuda-trusty.sh
  - source .travis/install-stack.sh
  - source .travis/update-ghc-settings.sh
  - travis_retry stack install c2hs --fast --no-terminal

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - c2hs --version
  - llc --version; true
  - opt --version; true
  - travis_retry travis_wait 60 stack build --only-dependencies --fast --jobs=2 --no-terminal --no-haddock-deps

script:
  - stack build --fast --jobs=2 --no-terminal --haddock --no-haddock-deps
  - stack test accelerate-blas:test-llvm-native --test-arguments='--hedgehog-tests 50'

after_success:
  - source .travis/update-accelerate-buildbot.sh

